#[doc = "Register `TIMG4_TSEL` reader"]
pub type R = crate::R<Timg4TselSpec>;
#[doc = "Register `TIMG4_TSEL` writer"]
pub type W = crate::W<Timg4TselSpec>;
#[doc = "External Trigger Select. #br# This selects which System Event is used if the input filter selects trigger. Triggers 0-15 are used to connect triggers generated by other timer modules in the same power domain. Refer to the SoC datasheet to get details. Triggers 16 and 17 are connected to event manager subscriber ports. Event lines 18-31 are reserved for future use.\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Etsel {
    #[doc = "0: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig0 = 0,
    #[doc = "1: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig1 = 1,
    #[doc = "2: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig2 = 2,
    #[doc = "3: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig3 = 3,
    #[doc = "4: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig4 = 4,
    #[doc = "5: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig5 = 5,
    #[doc = "6: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig6 = 6,
    #[doc = "7: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig7 = 7,
    #[doc = "8: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig8 = 8,
    #[doc = "9: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig9 = 9,
    #[doc = "10: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig10 = 10,
    #[doc = "11: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig11 = 11,
    #[doc = "12: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig12 = 12,
    #[doc = "13: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig13 = 13,
    #[doc = "14: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig14 = 14,
    #[doc = "15: TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    Trig15 = 15,
    #[doc = "16: TRIG_SUBx = External trigger input from subscriber port x."]
    TrigSub0 = 16,
    #[doc = "17: TRIG_SUBx = External trigger input from subscriber port x."]
    TrigSub1 = 17,
}
impl From<Etsel> for u8 {
    #[inline(always)]
    fn from(variant: Etsel) -> Self {
        variant as _
    }
}
impl crate::FieldSpec for Etsel {
    type Ux = u8;
}
impl crate::IsEnum for Etsel {}
#[doc = "Field `ETSEL` reader - External Trigger Select. #br# This selects which System Event is used if the input filter selects trigger. Triggers 0-15 are used to connect triggers generated by other timer modules in the same power domain. Refer to the SoC datasheet to get details. Triggers 16 and 17 are connected to event manager subscriber ports. Event lines 18-31 are reserved for future use."]
pub type EtselR = crate::FieldReader<Etsel>;
impl EtselR {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub const fn variant(&self) -> Option<Etsel> {
        match self.bits {
            0 => Some(Etsel::Trig0),
            1 => Some(Etsel::Trig1),
            2 => Some(Etsel::Trig2),
            3 => Some(Etsel::Trig3),
            4 => Some(Etsel::Trig4),
            5 => Some(Etsel::Trig5),
            6 => Some(Etsel::Trig6),
            7 => Some(Etsel::Trig7),
            8 => Some(Etsel::Trig8),
            9 => Some(Etsel::Trig9),
            10 => Some(Etsel::Trig10),
            11 => Some(Etsel::Trig11),
            12 => Some(Etsel::Trig12),
            13 => Some(Etsel::Trig13),
            14 => Some(Etsel::Trig14),
            15 => Some(Etsel::Trig15),
            16 => Some(Etsel::TrigSub0),
            17 => Some(Etsel::TrigSub1),
            _ => None,
        }
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig0(&self) -> bool {
        *self == Etsel::Trig0
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig1(&self) -> bool {
        *self == Etsel::Trig1
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig2(&self) -> bool {
        *self == Etsel::Trig2
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig3(&self) -> bool {
        *self == Etsel::Trig3
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig4(&self) -> bool {
        *self == Etsel::Trig4
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig5(&self) -> bool {
        *self == Etsel::Trig5
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig6(&self) -> bool {
        *self == Etsel::Trig6
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig7(&self) -> bool {
        *self == Etsel::Trig7
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig8(&self) -> bool {
        *self == Etsel::Trig8
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig9(&self) -> bool {
        *self == Etsel::Trig9
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig10(&self) -> bool {
        *self == Etsel::Trig10
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig11(&self) -> bool {
        *self == Etsel::Trig11
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig12(&self) -> bool {
        *self == Etsel::Trig12
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig13(&self) -> bool {
        *self == Etsel::Trig13
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig14(&self) -> bool {
        *self == Etsel::Trig14
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn is_trig15(&self) -> bool {
        *self == Etsel::Trig15
    }
    #[doc = "TRIG_SUBx = External trigger input from subscriber port x."]
    #[inline(always)]
    pub fn is_trig_sub0(&self) -> bool {
        *self == Etsel::TrigSub0
    }
    #[doc = "TRIG_SUBx = External trigger input from subscriber port x."]
    #[inline(always)]
    pub fn is_trig_sub1(&self) -> bool {
        *self == Etsel::TrigSub1
    }
}
#[doc = "Field `ETSEL` writer - External Trigger Select. #br# This selects which System Event is used if the input filter selects trigger. Triggers 0-15 are used to connect triggers generated by other timer modules in the same power domain. Refer to the SoC datasheet to get details. Triggers 16 and 17 are connected to event manager subscriber ports. Event lines 18-31 are reserved for future use."]
pub type EtselW<'a, REG> = crate::FieldWriter<'a, REG, 5, Etsel>;
impl<'a, REG> EtselW<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
    REG::Ux: From<u8>,
{
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig0(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig0)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig1(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig1)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig2(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig2)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig3(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig3)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig4(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig4)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig5(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig5)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig6(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig6)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig7(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig7)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig8(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig8)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig9(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig9)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig10(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig10)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig11(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig11)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig12(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig12)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig13(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig13)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig14(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig14)
    }
    #[doc = "TRIGx = External trigger input from timer x (if available) in the same power domain as the current timer."]
    #[inline(always)]
    pub fn trig15(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::Trig15)
    }
    #[doc = "TRIG_SUBx = External trigger input from subscriber port x."]
    #[inline(always)]
    pub fn trig_sub0(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::TrigSub0)
    }
    #[doc = "TRIG_SUBx = External trigger input from subscriber port x."]
    #[inline(always)]
    pub fn trig_sub1(self) -> &'a mut crate::W<REG> {
        self.variant(Etsel::TrigSub1)
    }
}
#[doc = "Trigger Enable. This selects whether a trigger is enabled or not for this counter 0x0 = Triggers are not used 0x1 = Triggers are used as selected by the ETSEL field\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Te {
    #[doc = "0: Triggers are not used."]
    Disabled = 0,
    #[doc = "1: Triggers are used as selected by the IE, ITSEL and ETSEL fields."]
    Enabled = 1,
}
impl From<Te> for bool {
    #[inline(always)]
    fn from(variant: Te) -> Self {
        variant as u8 != 0
    }
}
#[doc = "Field `TE` reader - Trigger Enable. This selects whether a trigger is enabled or not for this counter 0x0 = Triggers are not used 0x1 = Triggers are used as selected by the ETSEL field"]
pub type TeR = crate::BitReader<Te>;
impl TeR {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub const fn variant(&self) -> Te {
        match self.bits {
            false => Te::Disabled,
            true => Te::Enabled,
        }
    }
    #[doc = "Triggers are not used."]
    #[inline(always)]
    pub fn is_disabled(&self) -> bool {
        *self == Te::Disabled
    }
    #[doc = "Triggers are used as selected by the IE, ITSEL and ETSEL fields."]
    #[inline(always)]
    pub fn is_enabled(&self) -> bool {
        *self == Te::Enabled
    }
}
#[doc = "Field `TE` writer - Trigger Enable. This selects whether a trigger is enabled or not for this counter 0x0 = Triggers are not used 0x1 = Triggers are used as selected by the ETSEL field"]
pub type TeW<'a, REG> = crate::BitWriter<'a, REG, Te>;
impl<'a, REG> TeW<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    #[doc = "Triggers are not used."]
    #[inline(always)]
    pub fn disabled(self) -> &'a mut crate::W<REG> {
        self.variant(Te::Disabled)
    }
    #[doc = "Triggers are used as selected by the IE, ITSEL and ETSEL fields."]
    #[inline(always)]
    pub fn enabled(self) -> &'a mut crate::W<REG> {
        self.variant(Te::Enabled)
    }
}
impl R {
    #[doc = "Bits 0:4 - External Trigger Select. #br# This selects which System Event is used if the input filter selects trigger. Triggers 0-15 are used to connect triggers generated by other timer modules in the same power domain. Refer to the SoC datasheet to get details. Triggers 16 and 17 are connected to event manager subscriber ports. Event lines 18-31 are reserved for future use."]
    #[inline(always)]
    pub fn etsel(&self) -> EtselR {
        EtselR::new((self.bits & 0x1f) as u8)
    }
    #[doc = "Bit 9 - Trigger Enable. This selects whether a trigger is enabled or not for this counter 0x0 = Triggers are not used 0x1 = Triggers are used as selected by the ETSEL field"]
    #[inline(always)]
    pub fn te(&self) -> TeR {
        TeR::new(((self.bits >> 9) & 1) != 0)
    }
}
impl W {
    #[doc = "Bits 0:4 - External Trigger Select. #br# This selects which System Event is used if the input filter selects trigger. Triggers 0-15 are used to connect triggers generated by other timer modules in the same power domain. Refer to the SoC datasheet to get details. Triggers 16 and 17 are connected to event manager subscriber ports. Event lines 18-31 are reserved for future use."]
    #[inline(always)]
    pub fn etsel(&mut self) -> EtselW<'_, Timg4TselSpec> {
        EtselW::new(self, 0)
    }
    #[doc = "Bit 9 - Trigger Enable. This selects whether a trigger is enabled or not for this counter 0x0 = Triggers are not used 0x1 = Triggers are used as selected by the ETSEL field"]
    #[inline(always)]
    pub fn te(&mut self) -> TeW<'_, Timg4TselSpec> {
        TeW::new(self, 9)
    }
}
#[doc = "Trigger Select\n\nYou can [`read`](crate::Reg::read) this register and get [`timg4_tsel::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`timg4_tsel::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct Timg4TselSpec;
impl crate::RegisterSpec for Timg4TselSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`timg4_tsel::R`](R) reader structure"]
impl crate::Readable for Timg4TselSpec {}
#[doc = "`write(|w| ..)` method takes [`timg4_tsel::W`](W) writer structure"]
impl crate::Writable for Timg4TselSpec {
    type Safety = crate::Unsafe;
}
#[doc = "`reset()` method sets TIMG4_TSEL to value 0"]
impl crate::Resettable for Timg4TselSpec {}
