#![doc = "Peripheral access API for MSPM0L222X microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn INT_GROUP0();
    fn INT_GROUP1();
    fn TIMG12();
    fn UART4();
    fn ADC0();
    fn SPI0();
    fn SPI1();
    fn UART2();
    fn UART3();
    fn UART0();
    fn UART1();
    fn TIMA0();
    fn TIMG8();
    fn TIMG0();
    fn TIMG4();
    fn TIMG5();
    fn I2C0();
    fn I2C1();
    fn I2C2();
    fn AESADV();
    fn LCD0();
    fn LFSS();
    fn DMA0();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 32] = [
    Vector {
        _handler: INT_GROUP0,
    },
    Vector {
        _handler: INT_GROUP1,
    },
    Vector { _handler: TIMG12 },
    Vector { _handler: UART4 },
    Vector { _handler: ADC0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI0 },
    Vector { _handler: SPI1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: UART2 },
    Vector { _handler: UART3 },
    Vector { _handler: UART0 },
    Vector { _handler: UART1 },
    Vector { _reserved: 0 },
    Vector { _handler: TIMA0 },
    Vector { _reserved: 0 },
    Vector { _handler: TIMG8 },
    Vector { _handler: TIMG0 },
    Vector { _handler: TIMG4 },
    Vector { _handler: TIMG5 },
    Vector { _handler: I2C0 },
    Vector { _handler: I2C1 },
    Vector { _handler: I2C2 },
    Vector { _reserved: 0 },
    Vector { _handler: AESADV },
    Vector { _handler: LCD0 },
    Vector { _handler: LFSS },
    Vector { _handler: DMA0 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - SYSCTL interrupt (group 0, IIDX 6)"]
    INT_GROUP0 = 0,
    #[doc = "1 - GPIOC interrupt (group 1, IIDX 6)"]
    INT_GROUP1 = 1,
    #[doc = "2 - TIMG12"]
    TIMG12 = 2,
    #[doc = "3 - UART4"]
    UART4 = 3,
    #[doc = "4 - ADC0"]
    ADC0 = 4,
    #[doc = "9 - SPI0"]
    SPI0 = 9,
    #[doc = "10 - SPI1"]
    SPI1 = 10,
    #[doc = "13 - UART2"]
    UART2 = 13,
    #[doc = "14 - UART3"]
    UART3 = 14,
    #[doc = "15 - UART0"]
    UART0 = 15,
    #[doc = "16 - UART1"]
    UART1 = 16,
    #[doc = "18 - TIMA0"]
    TIMA0 = 18,
    #[doc = "20 - TIMG8"]
    TIMG8 = 20,
    #[doc = "21 - TIMG0"]
    TIMG0 = 21,
    #[doc = "22 - TIMG4"]
    TIMG4 = 22,
    #[doc = "23 - TIMG5"]
    TIMG5 = 23,
    #[doc = "24 - I2C0"]
    I2C0 = 24,
    #[doc = "25 - I2C1"]
    I2C1 = 25,
    #[doc = "26 - I2C2"]
    I2C2 = 26,
    #[doc = "28 - AESADV"]
    AESADV = 28,
    #[doc = "29 - LCD0"]
    LCD0 = 29,
    #[doc = "30 - LFSS"]
    LFSS = 30,
    #[doc = "31 - DMA0"]
    DMA0 = 31,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "DSSM"]
pub type Debugss = crate::Periph<debugss::RegisterBlock, 0x400c_7000>;
impl core::fmt::Debug for Debugss {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Debugss").finish()
    }
}
#[doc = "DSSM"]
pub mod debugss;
#[doc = "PERIPHERALREGION"]
pub type Comp0 = crate::Periph<comp0::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Comp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Comp0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod comp0;
#[doc = "WWDT"]
pub type Wwdt0 = crate::Periph<wwdt0::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for Wwdt0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wwdt0").finish()
    }
}
#[doc = "WWDT"]
pub mod wwdt0;
#[doc = "PERIPHERALREGION"]
pub type I2c1 = crate::Periph<i2c1::RegisterBlock, 0x400f_2000>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod i2c1;
#[doc = "PERIPHERALREGION"]
pub type Eventlp = crate::Periph<eventlp::RegisterBlock, 0x400c_9000>;
impl core::fmt::Debug for Eventlp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Eventlp").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod eventlp;
#[doc = "PERIPHERALREGION"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4010_8000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod uart0;
#[doc = "PERIPHERALREGION"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x400a_0000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod gpioa;
#[doc = "PERIPHERALREGION"]
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x400f_0000>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod i2c0;
#[doc = "PERIPHERALREGION"]
pub type Uart2 = crate::Periph<uart2::RegisterBlock, 0x4010_0000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod uart2;
#[doc = "PERIPHERALREGION"]
pub type Adc0 = crate::Periph<adc0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Adc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod adc0;
#[doc = "PERIPHERALREGIONSVT"]
pub type Adc0Svt = crate::Periph<adc0_svt::RegisterBlock, 0x4055_a000>;
impl core::fmt::Debug for Adc0Svt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc0Svt").finish()
    }
}
#[doc = "PERIPHERALREGIONSVT"]
pub mod adc0_svt;
#[doc = "PERIPHERALREGION"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x4046_8000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod spi0;
#[doc = "PERIPHERALREGION"]
pub type Vref = crate::Periph<vref::RegisterBlock, 0x4003_0000>;
impl core::fmt::Debug for Vref {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vref").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod vref;
#[doc = "PERIPHERALREGION"]
pub type Spi1 = crate::Periph<spi1::RegisterBlock, 0x4046_a000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod spi1;
#[doc = "PERIPHERALREGION"]
pub type Keystorectl = crate::Periph<keystorectl::RegisterBlock, 0x400a_c000>;
impl core::fmt::Debug for Keystorectl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Keystorectl").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod keystorectl;
#[doc = "PERIPHERALREGION"]
pub type Trng = crate::Periph<trng::RegisterBlock, 0x4044_4000>;
impl core::fmt::Debug for Trng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Trng").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod trng;
#[doc = "PERIPHERALREGION"]
pub type Uart3 = crate::Periph<uart3::RegisterBlock, 0x4010_2000>;
impl core::fmt::Debug for Uart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart3").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod uart3;
#[doc = "PERIPHERALREGION"]
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x4010_a000>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod uart1;
#[doc = "PERIPHERALREGION"]
pub type Uart4 = crate::Periph<uart4::RegisterBlock, 0x4010_4000>;
impl core::fmt::Debug for Uart4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart4").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod uart4;
#[doc = "PERIPHERALREGION"]
pub type I2c2 = crate::Periph<i2c2::RegisterBlock, 0x400f_4000>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod i2c2;
#[doc = "PERIPHERALREGION"]
pub type Gpiob = crate::Periph<gpiob::RegisterBlock, 0x400a_2000>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod gpiob;
#[doc = "PERIPHERALREGION"]
pub type Gpioc = crate::Periph<gpioc::RegisterBlock, 0x400a_4000>;
impl core::fmt::Debug for Gpioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioc").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod gpioc;
#[doc = "NVMNW_GANDALF"]
pub type Flashctl = crate::Periph<flashctl::RegisterBlock, 0x400c_d000>;
impl core::fmt::Debug for Flashctl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flashctl").finish()
    }
}
#[doc = "NVMNW_GANDALF"]
pub mod flashctl;
#[doc = "PERIPHERALREGION"]
pub type Aesadv = crate::Periph<aesadv::RegisterBlock, 0x4044_2000>;
impl core::fmt::Debug for Aesadv {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aesadv").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod aesadv;
#[doc = "PERIPHERALREGION"]
pub type Crcp0 = crate::Periph<crcp0::RegisterBlock, 0x4044_0000>;
impl core::fmt::Debug for Crcp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crcp0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod crcp0;
#[doc = "PERIPHERALREGION"]
pub type Timg0 = crate::Periph<timg0::RegisterBlock, 0x4008_4000>;
impl core::fmt::Debug for Timg0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timg0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod timg0;
#[doc = "PERIPHERALREGION"]
pub type Timg4 = crate::Periph<timg4::RegisterBlock, 0x4008_c000>;
impl core::fmt::Debug for Timg4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timg4").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod timg4;
#[doc = "PERIPHERALREGION"]
pub type Timg8 = crate::Periph<timg8::RegisterBlock, 0x4009_0000>;
impl core::fmt::Debug for Timg8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timg8").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod timg8;
#[doc = "PERIPHERALREGION"]
pub type Timg12 = crate::Periph<timg12::RegisterBlock, 0x4087_0000>;
impl core::fmt::Debug for Timg12 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timg12").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod timg12;
#[doc = "PERIPHERALREGION"]
pub type Tima0 = crate::Periph<tima0::RegisterBlock, 0x4086_0000>;
impl core::fmt::Debug for Tima0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tima0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod tima0;
#[doc = "PERIPHERALREGION"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4042_a000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod dma;
#[doc = "PERIPHERALREGION"]
pub type Lfss = crate::Periph<lfss::RegisterBlock, 0x4009_4000>;
impl core::fmt::Debug for Lfss {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lfss").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod lfss;
#[doc = "mem_map"]
pub type Sysctl = crate::Periph<sysctl::RegisterBlock, 0x400a_f000>;
impl core::fmt::Debug for Sysctl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sysctl").finish()
    }
}
#[doc = "mem_map"]
pub mod sysctl;
#[doc = "PERIPHERALREGION"]
pub type Timg5 = crate::Periph<timg5::RegisterBlock, 0x4008_e000>;
impl core::fmt::Debug for Timg5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timg5").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod timg5;
#[doc = "PERIPHERALREGION"]
pub type Iomux = crate::Periph<iomux::RegisterBlock, 0x4042_8000>;
impl core::fmt::Debug for Iomux {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iomux").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod iomux;
#[doc = "PERIPHERALREGION"]
pub type Lcd = crate::Periph<lcd::RegisterBlock, 0x4007_0000>;
impl core::fmt::Debug for Lcd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lcd").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod lcd;
#[doc = "CPUSSMMR"]
pub type Cpuss = crate::Periph<cpuss::RegisterBlock, 0x4040_0000>;
impl core::fmt::Debug for Cpuss {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cpuss").finish()
    }
}
#[doc = "CPUSSMMR"]
pub mod cpuss;
#[doc = "PERIPHERALREGION"]
pub type Wuc = crate::Periph<wuc::RegisterBlock, 0x4042_4000>;
impl core::fmt::Debug for Wuc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wuc").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod wuc;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "DEBUGSS"]
    pub debugss: Debugss,
    #[doc = "COMP0"]
    pub comp0: Comp0,
    #[doc = "WWDT0"]
    pub wwdt0: Wwdt0,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "EVENTLP"]
    pub eventlp: Eventlp,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "I2C0"]
    pub i2c0: I2c0,
    #[doc = "UART2"]
    pub uart2: Uart2,
    #[doc = "ADC0"]
    pub adc0: Adc0,
    #[doc = "ADC0_SVT"]
    pub adc0_svt: Adc0Svt,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "VREF"]
    pub vref: Vref,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "KEYSTORECTL"]
    pub keystorectl: Keystorectl,
    #[doc = "TRNG"]
    pub trng: Trng,
    #[doc = "UART3"]
    pub uart3: Uart3,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "UART4"]
    pub uart4: Uart4,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GPIOC"]
    pub gpioc: Gpioc,
    #[doc = "FLASHCTL"]
    pub flashctl: Flashctl,
    #[doc = "AESADV"]
    pub aesadv: Aesadv,
    #[doc = "CRCP0"]
    pub crcp0: Crcp0,
    #[doc = "TIMG0"]
    pub timg0: Timg0,
    #[doc = "TIMG4"]
    pub timg4: Timg4,
    #[doc = "TIMG8"]
    pub timg8: Timg8,
    #[doc = "TIMG12"]
    pub timg12: Timg12,
    #[doc = "TIMA0"]
    pub tima0: Tima0,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "LFSS"]
    pub lfss: Lfss,
    #[doc = "SYSCTL"]
    pub sysctl: Sysctl,
    #[doc = "TIMG5"]
    pub timg5: Timg5,
    #[doc = "IOMUX"]
    pub iomux: Iomux,
    #[doc = "LCD"]
    pub lcd: Lcd,
    #[doc = "CPUSS"]
    pub cpuss: Cpuss,
    #[doc = "WUC"]
    pub wuc: Wuc,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            debugss: Debugss::steal(),
            comp0: Comp0::steal(),
            wwdt0: Wwdt0::steal(),
            i2c1: I2c1::steal(),
            eventlp: Eventlp::steal(),
            uart0: Uart0::steal(),
            gpioa: Gpioa::steal(),
            i2c0: I2c0::steal(),
            uart2: Uart2::steal(),
            adc0: Adc0::steal(),
            adc0_svt: Adc0Svt::steal(),
            spi0: Spi0::steal(),
            vref: Vref::steal(),
            spi1: Spi1::steal(),
            keystorectl: Keystorectl::steal(),
            trng: Trng::steal(),
            uart3: Uart3::steal(),
            uart1: Uart1::steal(),
            uart4: Uart4::steal(),
            i2c2: I2c2::steal(),
            gpiob: Gpiob::steal(),
            gpioc: Gpioc::steal(),
            flashctl: Flashctl::steal(),
            aesadv: Aesadv::steal(),
            crcp0: Crcp0::steal(),
            timg0: Timg0::steal(),
            timg4: Timg4::steal(),
            timg8: Timg8::steal(),
            timg12: Timg12::steal(),
            tima0: Tima0::steal(),
            dma: Dma::steal(),
            lfss: Lfss::steal(),
            sysctl: Sysctl::steal(),
            timg5: Timg5::steal(),
            iomux: Iomux::steal(),
            lcd: Lcd::steal(),
            cpuss: Cpuss::steal(),
            wuc: Wuc::steal(),
        }
    }
}
